### PR TITLE
hotfix/APPEALS-65597

### PR DESCRIPTION
**Pull request by raymond-hughes**
Resolves [APPEALS-65597](https://jira.devops.va.gov/browse/APPEALS-65597)

# Description
Update PID Transformer to Allow Integer and String Values

## Acceptance Criteria
- [ ] Code compiles correctly

### CODE REVIEW

**Review by drew-hadley — DISMISSED** [review]
LGTM

**Review by dcoleman21 — APPROVED** [review]
I think this looks good as long as that file I asked you about is all set as well.

**Review by dcoleman21 — APPROVED** [review]
Did you decide just to string-a-fy everything vs making any changes to the db?

**Comment by raymond-hughes** [comment]
> caseflow_service.rb

Yeah it was easier than trying to add a new migration and make all of it ints. Since Caseflow is already a string it makes sense to keep it the same between CF and Consumer

**Pull request merged**
